# Copyright 2024 NVIDIA CORPORATION
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this workflow on pull requests
name: image

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

jobs:
  packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - ubuntu22.04-arm64
          - ubuntu22.04-amd64
          - ubuntu22.04-ppc64le
          - ubuntu20.04-arm64
          - ubuntu20.04-amd64
          - ubuntu20.04-ppc64le
          # - ubuntu18.04-arm64
          # - ubuntu18.04-amd64
          # - ubuntu18.04-ppc64le
          - centos7-aarch64
          - centos7-x86_64
          - centos8-ppc64le
        do-not-build:
          - ${{ !(github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-')) || github.event_name == 'pull_request' || github.actor == 'dependabot[bot]' }}
        exclude:
          # - do-not-build: true
          #   target: ubuntu22.04-arm64
          - do-not-build: true
            target: ubuntu22.04-ppc64le
          - do-not-build: true
            target: ubuntu20.04-amd64
          - do-not-build: true
            target: ubuntu20.04-arm64
          - do-not-build: true
            target: ubuntu20.04-ppc64le
          # - do-not-build: true
          #   target: ubuntu18.04-amd64
          # - do-not-build: true
          #   target: ubuntu18.04-arm64
          # - do-not-build: true
          #   target: ubuntu18.04-ppc64le
          - do-not-build: true
            target: centos7-aarch64
          - do-not-build: true
            target: centos8-ppc64le
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build ${{ matrix.target }} packages
        run: |
          sudo apt-get install -y coreutils build-essential sed git bash make
          echo "Building packages"
          ./scripts/build-packages.sh ${{ matrix.target }}
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: toolkit-container-${{ matrix.target }}-${{ github.run_id }}
          path: ${{ github.workspace }}/dist/*

  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - ubuntu22.04
          - ubuntu20.04
          - ubi8
          - packaging
        do-not-build:
          - ${{ !(github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-')) || github.event_name == 'pull_request' || github.actor == 'dependabot[bot]' }}
        exclude:
          - do-not-build: true
            dist: ubuntu20.04
          - do-not-build: true
            dist: ubi8
    needs: packages
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - name: Calculate build vars
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          echo "LOWERCASE_REPO_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | awk '{print tolower($0)}')" >> $GITHUB_ENV
          REPO_FULL_NAME="${{ github.event.pull_request.head.repo.full_name }}"
          echo "${REPO_FULL_NAME}"
          echo "LABEL_IMAGE_SOURCE=https://github.com/${REPO_FULL_NAME}" >> $GITHUB_ENV

          PUSH_ON_BUILD="false"
          BUILD_MULTI_ARCH_IMAGES="false"
          DOCKER_BUILD_PLATFORM_OPTIONS=""

          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            PUSH_ON_BUILD="false"
            BUILD_MULTI_ARCH_IMAGES="false"
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            PUSH_ON_BUILD="true"
            BUILD_MULTI_ARCH_IMAGES="true"
            DOCKER_BUILD_PLATFORM_OPTIONS="--platform=linux/amd64,linux/arm64"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PUSH_ON_BUILD="false"
            BUILD_MULTI_ARCH_IMAGES="true"
            DOCKER_BUILD_PLATFORM_OPTIONS="--platform=linux/amd64,linux/arm64"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-') }}" == "true" ]]; then
            PUSH_ON_BUILD="true"
            BUILD_MULTI_ARCH_IMAGES="true"
            if [[ "${{ matrix.dist == 'ubi8'}}" == "true" ]]; then
              DOCKER_BUILD_PLATFORM_OPTIONS="--platform=linux/amd64,linux/arm64,linux/ppc64le"
            elif [[ "${{ matrix.dist == 'ubuntu18.04'}}" == "true" ]]; then
              DOCKER_BUILD_PLATFORM_OPTIONS="--platform=linux/amd64"
            elif [[ "${{ matrix.dist == 'packaging'}}" == "true" ]]; then
              DOCKER_BUILD_PLATFORM_OPTIONS="--platform=linux/amd64"
            else
              DOCKER_BUILD_PLATFORM_OPTIONS="--platform=linux/amd64,linux/arm64"
            fi
          fi

          echo "PUSH_ON_BUILD=${PUSH_ON_BUILD}" >> $GITHUB_ENV
          echo "BUILD_MULTI_ARCH_IMAGES=${BUILD_MULTI_ARCH_IMAGES}" >> $GITHUB_ENV
          echo "DOCKER_BUILD_PLATFORM_OPTIONS=${DOCKER_BUILD_PLATFORM_OPTIONS}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get built packages
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/dist/
          pattern: toolkit-container-${{ matrix.dist == 'packaging' && '*' || format('{0}-*', matrix.dist == 'ubi8' && 'centos7' || matrix.dist) }}-${{ github.run_id }}
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        env:
          BUILDIMAGE: ghcr.io/${LOWERCASE_REPO_OWNER}/k8s-test-infra:devel-go${GOLANG_VERSION}
          IMAGE_NAME: ghcr.io/${LOWERCASE_REPO_OWNER}/container-toolkit
          VERSION: ${COMMIT_SHORT_SHA}
        run: |
          echo "${VERSION}"
          make -f deployments/container/Makefile build-${{ matrix.dist }}
